/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class company_co_kr_videoplayer_AudioPlayer */

#ifndef _Included_company_co_kr_videoplayer_AudioPlayer
#define _Included_company_co_kr_videoplayer_AudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     company_co_kr_videoplayer_AudioPlayer
 * Method:    nativePlayAudio
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_company_co_kr_videoplayer_AudioPlayer_nativePlayAudio
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
