/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class company_co_kr_videoplayer_VideoPlayer */

#ifndef _Included_company_co_kr_videoplayer_VideoPlayer
#define _Included_company_co_kr_videoplayer_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     company_co_kr_videoplayer_VideoPlayer
 * Method:    nativePlay
 * Signature: (Landroid/view/Surface;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_company_co_kr_videoplayer_VideoPlayer_nativePlay
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     company_co_kr_videoplayer_VideoPlayer
 * Method:    nativeStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_company_co_kr_videoplayer_VideoPlayer_nativeStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
